import "../../styles/nuevos.css"

export function Nosotros() {
    return (
      <div className="body">

        <h2>ACERCA DE NOSOTROS</h2>	

        <p>SOMOS LA PRIMERA MULTIMARCA FEDERAL DEDICADA A LA COMERCIALIZACIÓN DE UNIDADES 0KM NACIONALES E IMPORTADAS.</p>
        <p>NUESTRA CASA MATRÍZ FUE FUNDADA EN LA CIUDAD DE BUENOS AIRES EN MARZO DE 1967.</p>
        <p>EN LA CIUDAD DE USHUAIA, NUESTRA ÚLTIMA APERTURA, ESTAMOS DESDE JULIO DEL 2008.</p> 
        <p>NUESTRO SERVICIO DE ATENCIÓN POST VENTA CUENTA CON LA MEJOR TECNOLOGÍA INSTALADA DEL PAÍS.</p>
        <p>LOS REPUESTOS Y ACCESORIOS DE EXCELENCIA NOS UBICAN EN EL 1º PUESTO EN EL MERCADO AUTOMOTOR.</p>
        <p>LA CORDIALIDAD Y EL PROFESIONALISMO SON NUESTROS ATRIBUTOS FUNDAMENTALES.</p>  

      </div>
    );
}
